queriesList={
    "1":"SELECT   ?uniname ?courses ?coursecode ?coursenumber WHERE {{ ?uname Vocab:name ?x. ?course Vocab:belongs_to ?uiversityname; Vocab:course_name ?courses; Vocab:course_subject ?coursecode; Vocab:course_number ?coursenumber. FILTER (lcase(str(?x)) = '{}')}}",
    "2":"SELECT DISTINCT ?coursename ?coursecode ?coursenumber WHERE {{?topic Vocab:topic_name ?x. ?topic Vocab:belongs_to ?course.?course Vocab:course_name ?coursename;Vocab:course_subject ?coursecode; Vocab:course_number ?coursenumber. FILTER (lcase(str(?x)) = '{}')}}",
    "3":"SELECT DISTINCT ?topic ?cname ?lecnum WHERE {{?course rdf:type vivo:Course .?course ?p ?x. ?lecture Vocab:belongs_to ?course. ?lecture Vocab:lecture_number ?y. ?topicUri Vocab:taught_in ?lecture. ?topicUri Vocab:topic_name ?topic . ?course Vocab:course_name ?cname. ?lecture Vocab:lecture_number ?lecnum. FILTER (lcase(str(?x)) = '{}')  FILTER (lcase(str(?y)) = '{}')}}",
    "3A":"SELECT DISTINCT ?topic ?cname ?lecnum WHERE {{?course rdf:type vivo:Course .?course ?p ?x. ?course ?p2 ?z . ?lecture Vocab:belongs_to ?course. ?lecture Vocab:lecture_number ?y. ?topicUri Vocab:taught_in ?lecture. ?topicUri Vocab:topic_name ?topic . ?course Vocab:course_name ?cname. ?lecture Vocab:lecture_number ?lecnum. FILTER (lcase(str(?x)) = '{}') FILTER(lcase(str(?z)) = '{}') FILTER (lcase(str(?y)) = '{}')}}",
    "4":"SELECT DISTINCT ?courses ?coursecode ?coursenumber ?uniname ?subject WHERE {{ ?uname Vocab:name ?x. ?course Vocab:belongs_to ?uname.?course Vocab:course_name ?courses;Vocab:course_subject ?coursecode; Vocab:course_number ?coursenumber. ?uname Vocab:name ?uniname .?course Vocab:course_subject ?subject. FILTER (lcase(str(?x)) = '{}') FILTER(lcase(str(?subject))='{}'). }}",
    "5":"SELECT DISTINCT ?x WHERE {{ ?s Vocab:course_number ?cnum; Vocab:course_subject ?ccode. ?topic Vocab:belongs_to ?s; Vocab:topic_name ?topic_name. ?topic Vocab:topic_name ?tname. ?topic Vocab:taught_in ?lec. ?lec Vocab:has_Content ?x. ?x rdf:type ?y. ?y rdfs:label ?clabel. ?y rdfs:label ?label FILTER (lcase(str(?cnum)) = '{}') FILTER (lcase(str(?ccode)) = '{}') FILTER (lcase(str(?tname)) = '{}') FILTER (lcase(str(?clabel)) = '{}')}}",
    "5A":"SELECT DISTINCT ?x WHERE {{ ?s Vocab:course_name ?cname; Vocab:course_subject ?ccode. ?topic Vocab:belongs_to ?s; Vocab:topic_name ?topic_name. ?topic Vocab:topic_name ?tname. ?topic Vocab:taught_in ?lec. ?lec Vocab:has_Content ?x. ?x rdf:type ?y. ?y rdfs:label ?clabel. ?y rdfs:label ?label FILTER (lcase(str(?cname)) = '{}')  FILTER (lcase(str(?tname)) = '{}') FILTER (lcase(str(?clabel)) = '{}')}}",
    "6":"SELECT DISTINCT ?credits WHERE {{ ?course Vocab:course_number ?cnum ;Vocab:course_subject ?ccode; Vocab:has_credits ?credits .FILTER (lcase(str(?cnum)) = '{}') FILTER (lcase(str(?ccode))= '{}') }}",
    "7":"select ?url WHERE {{ ?s Vocab:course_number ?cnum;Vocab:course_subject ?ccode . ?s rdfs:seeAlso ?url. FILTER (lcase(str(?cnum)) = '{}') FILTER (lcase(str(?ccode))= '{}') }}",
    "7A":"select ?url WHERE {{ ?s Vocab:course_name ?cname . ?s rdfs:seeAlso ?url. FILTER (lcase(str(?cname)) = '{}') }}",
    "8":"select ?material ?cname ?lnum ?cnum (COUNT(?material) AS ?count) WHERE {{?s Vocab:course_number ?cnum; Vocab:course_subject ?ccode. ?lec Vocab:belongs_to ?s;Vocab:lecture_number ?lnum;Vocab:has_Content ?x. ?x rdf:type ?y. ?y rdfs:label ?material. ?lec Vocab:lecture_number ?lnum. FILTER (lcase(str(?cnum)) = '{}') FILTER (lcase(str(?ccode)) = '{}') FILTER (lcase(str(?lnum)) = '{}')}} GROUP BY ?material ?cname ?lnum ?cnum",
    "8A":"select ?material ?cname ?lnum ?cnum (COUNT(?material) AS ?count) WHERE {{?s Vocab:course_name ?cname. ?lec Vocab:belongs_to ?s;Vocab:lecture_number ?lnum;Vocab:has_Content ?x. ?x rdf:type ?y. ?y rdfs:label ?material. ?lec Vocab:lecture_number ?lnum. FILTER (lcase(str(?cname)) = '{}')  FILTER (lcase(str(?lnum)) = '{}')}} GROUP BY ?material ?cname ?lnum ?cnum",
    "9":"SELECT DISTINCT ?readingstuff WHERE {{ ?s Vocab:course_number ?cnum;Vocab:course_subject ?ccode. ?topic Vocab:belongs_to ?s. ?topic Vocab:topic_name ?tname. ?topic Vocab:taught_in ?lec. ?lec Vocab:has_Content ?readingstuff. FILTER (lcase(str(?cnum)) = '{}') FILTER (lcase(str(?ccode)) = '{}') FILTER (lcase(str(?tname)) = '{}')}}",
    "9A":"SELECT DISTINCT ?readingstuff WHERE {{ ?s Vocab:course_name ?cname. ?topic Vocab:belongs_to ?s. ?topic Vocab:topic_name ?tname. ?topic Vocab:taught_in ?lec. ?lec Vocab:has_Content ?readingstuff.  FILTER (lcase(str(?cname)) = '{}') FILTER (lcase(str(?tname)) = '{}')}}",
    "10":"select DISTINCT ?topicname WHERE {{ ?s Vocab:course_number '{}';Vocab:course_subject ?ccode. ?topic Vocab:belongs_to ?s. ?topic Vocab:topic_name ?topicname FILTER (lcase(str(?ccode)) = '{}')}}",
    "10A":"select DISTINCT ?topicname WHERE {{ ?s Vocab:course_name ?cname. ?topic Vocab:belongs_to ?s. ?topic Vocab:topic_name ?topicname FILTER (lcase(str(?cname)) = '{}')}}",
    "11":"select ?grade  WHERE {{  ?s Vocab:student_name ?name. ?name foaf:firstName ?fname. ?name foaf:lastName ?lname .?s Vocab:completed_courses ?scourses. ?scourses Vocab:course ?course. ?course Vocab:course_number ?cnum;Vocab:course_subject ?ccode. ?scourses Vocab:grade ?grade. FILTER (lcase(str(?cnum)) = '{}') FILTER (lcase(str(?ccode)) = '{}') FILTER (lcase(str(?fname)) = '{}') FILTER (lcase(str(?lname)) = '{}')}}",
    "11A":"select ?grade  WHERE {{  ?s Vocab:student_id ?id . ?s Vocab:completed_courses ?scourses. ?scourses Vocab:course ?course. ?course Vocab:course_number ?cnum;Vocab:course_subject ?ccode. ?scourses Vocab:grade ?grade. FILTER (lcase(str(?cnum)) = '{}') FILTER (lcase(str(?ccode)) = '{}') FILTER (lcase(str(?id)) = '{}') }}",
    "11C":"select ?grade  WHERE {{  ?s Vocab:student_id ?id . ?s Vocab:completed_courses ?scourses. ?scourses Vocab:course ?course. ?course Vocab:course_name ?cname . ?scourses Vocab:grade ?grade.  FILTER (lcase(str(?cname)) = '{}') FILTER (lcase(str(?id)) = '{}') }}",
    "11B":"select ?grade  WHERE {{  ?s Vocab:student_name ?name. ?name foaf:firstName ?fname. ?name foaf:lastName ?lname .?s Vocab:completed_courses ?scourses. ?scourses Vocab:course ?course. ?course Vocab:course_name ?cname. ?scourses Vocab:grade ?grade.  FILTER (lcase(str(?cname)) = '{}') FILTER (lcase(str(?fname)) = '{}') FILTER (lcase(str(?lname)) = '{}')}}",
    "12":"select DISTINCT ?student_id ?firstname ?lastname  WHERE {{  ?s rdf:type vivo:Student. ?s Vocab:student_name ?name. ?name foaf:firstName ?firstname. ?name foaf:lastName ?lastname. ?s Vocab:completed_courses ?scourses;Vocab:student_id ?student_id. ?scourses Vocab:course ?course. ?course Vocab:course_subject ?ccode. ?course Vocab:course_number ?cnum. FILTER  (lcase(str(?cnum)) = '{}') FILTER (lcase(str(?ccode))=  '{}') }} ",
    "12A":"select DISTINCT ?student_id ?firstname ?lastname  WHERE {{  ?s rdf:type vivo:Student. ?s Vocab:student_name ?name. ?name foaf:firstName ?firstname. ?name foaf:lastName ?lastname. ?s Vocab:completed_courses ?scourses;Vocab:student_id ?student_id. ?scourses Vocab:course ?course. ?course Vocab:course_name ?cname. FILTER  (lcase(str(?cname)) = '{}') }} ",
    "13":"select DISTINCT ?id ?firstname ?lastname ?coursecode ?coursenumber ?coursename ?grade ?retook WHERE {{ ?s rdf:type vivo:Student. ?s Vocab:student_name ?name. ?name foaf:firstName ?fname. ?name foaf:lastName ?lname. ?s Vocab:student_id ?id . ?s Vocab:completed_courses ?scourses. ?scourses Vocab:course ?course. ?course Vocab:course_subject ?coursecode. ?course Vocab:course_number ?coursenumber. ?course Vocab:course_name ?coursename. ?scourses Vocab:grade ?grade. ?scourses Vocab:retookCourse ?retook. FILTER (lcase(str(?fname)) = '{}') FILTER (lcase(str(?lname)) = '{}') }}",
    "13A":"select DISTINCT ?id ?firstname ?lastname ?coursecode ?coursenumber ?coursename ?grade ?retook WHERE {{ ?s rdf:type vivo:Student. ?s Vocab:student_name ?name. ?name foaf:firstName ?fname. ?name foaf:lastName ?lname. ?s Vocab:student_id ?id . ?s Vocab:completed_courses ?scourses. ?scourses Vocab:course ?course. ?course Vocab:course_subject ?coursecode. ?course Vocab:course_number ?coursenumber. ?course Vocab:course_name ?coursename. ?scourses Vocab:grade ?grade. ?scourses Vocab:retookCourse ?retook. FILTER (lcase(str(?id)) = '{}') }}",
    "14": "select ?desc   WHERE {{ ?s Vocab:course_name ?cname. ?s Vocab:course_description ?desc FILTER (lcase(str(?cname)) = '{}')}}",
    "14A": "select ?desc   WHERE {{ ?s Vocab:course_number ?cnum;Vocab:course_subject ?ccode . ?s Vocab:course_description ?desc FILTER (lcase(str(?cnum)) = '{}') FILTER (lcase(str(?ccode)) = '{}')}}",
    "15": "select ?topics ?dblink ?wikilink  WHERE {{ ?s Vocab:course_number ?cnum;Vocab:course_subject ?ccode .?lec Vocab:belongs_to ?s; Vocab:has_Content ?content; Vocab:lecture_number ?lnum. ?content rdf:type ?something. ?something rdfs:label ?event. ?topic Vocab:taught_in ?lec. ?topic Vocab:provenance ?content; Vocab:topic_name ?topics. OPTIONAL{{?topic Vocab:dbpedia_Link ?dblink }} OPTIONAL{{?topic Vocab:wikidata_Link ?wikilink }} FILTER (lcase(str(?cnum)) = '{}') FILTER (lcase(str(?ccode)) = '{}') FILTER (lcase(str(?lnum)) = '{}' ) {} }}",
    "15A":"select ?topics ?dblink ?wikilink  WHERE {{ ?s Vocab:course_name ?cname .?lec Vocab:belongs_to ?s; Vocab:has_Content ?content; Vocab:lecture_number ?lnum. ?content rdf:type ?something. ?something rdfs:label ?event. ?topic Vocab:taught_in ?lec. ?topic Vocab:provenance ?content; Vocab:topic_name ?topics. OPTIONAL{{?topic Vocab:dbpedia_Link ?dblink }} OPTIONAL{{?topic Vocab:wikidata_Link ?wikilink }}  FILTER (lcase(str(?cname)) = '{}') FILTER (lcase(str(?lnum)) = '{}' ) {} }}",
    "16": "SELECT ?tname (COUNT(?tname) as ?count)  ?ccode ?cnum ?cname ?event ?lnum WHERE {{ ?course Vocab:course_name ?cname; Vocab:course_subject ?ccode; Vocab:course_number ?cnum. ?lec Vocab:belongs_to ?course; Vocab:lecture_number ?lnum. ?topic Vocab:taught_in ?lec;Vocab:topic_name ?tname;Vocab:provenance ?content. ?content a ?something. ?something rdfs:label ?labels.BIND(IF(?labels = 'lab content', 'LAB', 'LECTURE') AS ?event)  FILTER(lcase(str(?tname)) = '{}')}} GROUP BY ?ccode ?cnum ?cname ?event ?tname ?lnum ORDER BY DESC(?count)"
}



